sudo: required
services:
 - docker
before_install:

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker build -t abadoom/worker-app-test -f ./Prime/Dockerfile.dev ./Prime

script:
 - docker run abadoom/worker-app-test 
 - docker exec -it python code/worker1/manage.py test