FROM python:3.7

RUN pip install --upgrade pip
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt


EXPOSE 8000

WORKDIR /code

COPY . ./code

# runs the production server
ENTRYPOINT ["python", "code/worker1/manage.py"]
CMD ["test"]